### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Ryder17z** [kodybrown/sortxml#7]
```
C:\Users\ExileFox\Documents\sortxml-develop\bin\Debug>sortxml.exe Cards.dat Cards_XML.xml

Unhandled Exception: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at sortxml.Program.SortDelegate(XmlNode a, XmlNode b) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 196
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at sortxml.Program.SortNodes(XmlNode node) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 175
   at sortxml.Program.SortNodes(XmlNode node) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 163
   at sortxml.Program.SortNodes(XmlNode node) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 163
   at sortxml.Program.SortNodes(XmlNode node) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 163
   at sortxml.Program.SortNodes(XmlNode node) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 163
   at sortxml.Program.Main(String[] arguments) in C:\Users\ExileFox\Documents\unityripper\sortxml-develop\Program.cs:line 129
```

**Comment by kodybrown** [comment]
Can you provide the xml file you are trying to sort?

**Comment by Ryder17z** [comment]
[dat.txt](https://github.com/kodybrown/sortxml/files/4707594/dat.txt)

I was looking for a way to sort this. Eventually, I just wrote something quick and dirty to do it for me.
This is one of a bunch of different similarly structured files.

**Comment by iguy0** [comment]
Could be related...

`PS C:\Tools\sortxml> .\sortxml.exe /s /i .\sysmonconfig.xml .\out.xml
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at sortxml.Program.SortDelegate(XmlNode a, XmlNode b)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, Comparison`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, Comparison`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at sortxml.Program.SortNodes(XmlNode node)
   at sortxml.Program.SortNodes(XmlNode node)
   at sortxml.Program.SortNodes(XmlNode node)
   at sortxml.Program.SortNodes(XmlNode node)
   at sortxml.Program.Main(String[] arguments)`

XML file from: https://github.com/SwiftOnSecurity/sysmon-config/blob/master/sysmonconfig-export.xml
